Improved comparator
mskcc/smile-commons pull request #36
Opened 2022-09-01 15:36 UTC by divyamadala30

Signed-off-by: Divya Madala <71040191+divyamadala30@users.noreply.github.com>

Briefly describe changes proposed in this pull request:
- Comparator now recognizes changes in libraries, qcReports and runs in SampleMetadata level

--- 
## Crossing T's and dotting I's

Please follow these checklists to help prevent any unexpected issues from being introduced by the changes in this pull request. If an item does not apply then indicate so by surrounding the line item with `~~` to strikethrough the text. See [basic writing and formatting syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for more information.

### Mocked request data and data model checklist:

**Data checks:**
Updates were made to the mocked incoming request data and/or mocked published request data:
- [ ] [smile-server test data](https://github.com/mskcc/smile-server/tree/master/service/src/test/resources/data)
- [x] [smile-commons test data](https://github.com/mskcc/smile-commons/tree/master/src/test/resources/data)
- [ ] [smile-label-generator test data](https://github.com/mskcc/smile-label-generator/tree/master/src/test/resources/data)
- [ ] [smile-request-filter test data](https://github.com/mskcc/smile-request-filter/tree/master/src/test/resources/data)

**Code checks:**
- [x] The JSON comparator code been updated to handle new changes.
- [x] Unit tests were updated in relation to updates to the mocked test data.

**Describe your testing environment:**

- NATS [local, local docker, dev server, production]
- Neo4j [local, local docker, dev server, production]
- SMILE Server [local, local docker, dev server, production]
- Message publishing simulation [nats cli, docker nats cli, smile publisher tool, other (describe below)]

Other: Didn't use any of the above to test

### General checklist:
- [ ] All requested changes and comments have been resolved.
- [ ] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)

2022-09-01 15:37 UTC, divyamadala30 commented on src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java
> +    private Boolean isMatchingJsonByFieldName(JsonNode refNode, JsonNode tarNode, String fieldName) {
Maybe a better name for these methods...

2022-09-01 15:38 UTC, divyamadala30 commented on src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java
> +    private Boolean isMatchingJsonByFieldName(JsonNode refNode, JsonNode tarNode, String fieldName) {
Also should I add descriptions to these methods?

2022-09-01 16:06 UTC, ao508 requested changes

2022-09-01 16:06 UTC, ao508 commented on src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java
> +                if (refSampleNode.has("primaryId")) {
Maybe make this check for either `primaryId` or `igoId`?

2022-09-01 16:06 UTC, ao508 commented on src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java
> +                            refSampleNode.get("primaryId").toString());
same comment here - finding a sample node by a either `primaryId` or `igoId`

2022-09-01 16:06 UTC, ao508 commented on src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java
> +                        consistencyCheckStatus = Boolean.FALSE;
I like this though - I think it makes the most sense to do it this way

2022-09-01 16:06 UTC, ao508 commented on src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java
> +            if (primaryId.equals(sampleNode.get("primaryId").toString())) {
primaryId or igoId

2022-09-06 17:56 UTC, ao508 requested changes

2022-09-06 17:56 UTC, ao508 commented on src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java
> +                                    tarSampleNode.get("libraries"), "runs")) {
remove check on `runs`

2022-09-06 17:56 UTC, ao508 commented on src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java
> +
extra new line (also needs javadoc)

2022-09-06 19:01 UTC, ao508 approved these changes

2022-09-06 19:01 UTC, merged